### ISSUE TITLE
Gangway does not display username

### ISSUE THREAD

**Issue by VihanAgarwal97** [heptiolabs/gangway#172]
I am trying to install the Google OAuth Gangway integration on k8s. Everything seems to be working fine, but when I access the gangway service endpoint, I see a long token instead of the user's google email. 
Any idea how to fix this issue?

<img width="1149" alt="Image 2020-09-25 at 8 38 01 PM" src="https://user-images.githubusercontent.com/24706134/94326113-127fb200-ff70-11ea-9e15-f1417da16255.png">

I had to fork the helm chart because of https://github.com/helm/charts/issues/23785. Here are the values I am using - 
```
        gangway:
          scopes: ["openid", "profile", "email"]
          apiServerURL: "<redacted>"
          authorizeURL: "https://accounts.google.com/o/oauth2/auth"
          tokenURL: "https://www.googleapis.com/oauth2/v4/token"
          clusterName: <redacted>
          redirectURL: "http://<redacted>/callback"
          usernameClaim: "sub"
          emailClaim: "email"
        env: 
        - name: GANGWAY_SESSION_SECURITY_KEY
          valueFrom:
            secretKeyRef:
              name: gangway-key
              key: sessionkey 
        - name: GANGWAY_AUDIENCE
          valueFrom:
            secretKeyRef:
              name: gangway-secret 
              key: client_id 
        - name: GANGWAY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: gangway-secret 
              key: client_id
        - name: GANGWAY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: gangway-secret
              key: client_secret 
```
What am I misisng?
