### ISSUE TITLE
Support for path based routing

### ISSUE THREAD

**Issue by dkirrane** [heptiolabs/gangway#41]
Hi, is there anyway to set the base directory (root context) for gangway?
I have a single DNS entry for my cluster and I use path-based routing to the various UIs in my Ingress resources i.e. `path: /gangway`

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gangway
  namespace: gangway
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: mycluster.example.com
    http:
      paths:
      - backend:
          serviceName: gangwaysvc
          servicePort: http
        path: /gangway
  tls:
  - hosts:
    - mycluster.example.com
    secretName: my-tls
```

The problem is the gangway `SIGN IN` button routes to `https://mycluster.example.com/login/` instead of `https://mycluster.example.com/gangway/login`
![image](https://user-images.githubusercontent.com/1280116/44002778-38f1bf3e-9e40-11e8-842e-6de58072f473.png)

Click Sign In and you hit the default backend `https://mycluster.example.com/login`:

![image](https://user-images.githubusercontent.com/1280116/47214584-48848680-d396-11e8-98c0-a69a4c847314.png)
