### ISSUE TITLE
self-sign certificate?

### ISSUE THREAD

**Issue by rlagutinhub** [heptiolabs/gangway#74]
How to solve a problem with self-sign certificate?
Post https://dex.k8s.example.com/token: x509: certificate signed by unknown authority﻿

**Comment by stevesloka** [comment]
Hey @rlagutinhub which step in the process do you get that error? The flow should look like this:

1. Click "Login" from Gangway
2. Redirect to Dex
3. Redirect to Identity Provider (e.x. Google)
4. Redirect back to Gangway

**Comment by rlagutinhub** [comment]
Redirect to Dex

**Comment by stevesloka** [comment]
You could look to set the trusted-ca config param (https://github.com/heptiolabs/gangway/blob/master/cmd/gangway/config.go#L46:2).

**Comment by rlagutinhub** [comment]
![123](https://user-images.githubusercontent.com/30324030/47535646-18247700-d8c5-11e8-9120-cc491db8db36.png)

with TrustedCAPath param **not work**

**My current config gangway:**

apiVersion: v1
kind: ConfigMap
metadata:
  name: gangway
  namespace: gangway
data:
  gangway.yaml: |
    # The address to listen on. Defaults to 0.0.0.0 to listen on all interfaces.
    # Env var: GANGWAY_HOST
    # host: 0.0.0.0

    # The port to listen on. Defaults to 8080.
    # Env var: GANGWAY_PORT
    # port: 8080

    # Should Gangway serve TLS vs. plain HTTP? Default: false
    # Env var: GANGWAY_SERVE_TLS
    # serveTLS: false

    # The public cert file (including root and intermediates) to use when serving
    # TLS.
    # Env var: GANGWAY_CERT_FILE
    # certFile: /etc/gangway/tls/tls.crt

    # The private key file when serving TLS.
    # Env var: GANGWAY_KEY_FILE
    # keyFile: /etc/gangway/tls/tls.key

    TrustedCAPath: /etc/gangway/tls/ca.pem

    # The cluster name. Used in UI and kubectl config instructions.
    # Env var: GANGWAY_CLUSTER_NAME
    # clusterName: "${GANGWAY_CLUSTER_NAME}"
    clusterName: "MTA4RU"

    # OAuth2 URL to start authorization flow.
    # Env var: GANGWAY_AUTHORIZE_URL
    # authorizeURL: "https://${DNS_NAME}/authorize"
    authorizeURL: "https://dex.k8s.dev.mta4.ru/auth"

    # OAuth2 URL to obtain access tokens.
    # Env var: GANGWAY_TOKEN_URL
    # tokenURL: "https://${DNS_NAME}/oauth/token"
    tokenURL: "https://dex.k8s.dev.mta4.ru/token"

    # Endpoint that provides user profile information [optional]. Not all providers
    # will require this.
    # Env var: GANGWAY_AUDIENCE
    # audience: "https://${DNS_NAME}/userinfo"

    # Used to specify the scope of the requested Oauth authorization.
    # scopes: ["openid", "profile", "email", "offline_access"]
    scopes: ["openid", "profile", "email", "offline_access"]

    # Where to redirect back to. This should be a URL where gangway is reachable.
    # Typically this also needs to be registered as part of the oauth application
    # with the oAuth provider.
    # Env var: GANGWAY_REDIRECT_URL
    # redirectURL: "https://${GANGWAY_REDIRECT_URL}/callback"
    redirectURL: "https://gangway.k8s.dev.mta4.ru/callback"

    # API client ID as indicated by the identity provider
    # Env var: GANGWAY_CLIENT_ID
    # clientID: "${GANGWAY_CLIENT_ID}"
    clientID: "gangway"

    # API client secret as indicated by the identity provider
    # Env var: GANGWAY_CLIENT_SECRET
    # clientSecret: "${GANGWAY_CLIENT_SECRET}"
    clientSecret: "UncOnocvsJ5mT2FCX6oimZahAJkCtlUHa/a1zqs/gPo="

    # The JWT claim to use as the username. This is used in UI.
    # Default is "nickname".
    # Env var: GANGWAY_USERNAME_CLAIM
    # usernameClaim: "sub"
    usernameClaim: "email"

    # The JWT claim to use as the email claim. This is used to name the
    # "user" part of the config. Default is "email".
    # Env var: GANGWAY_EMAIL_CLAIM
    emailClaim: "email"

    # The API server endpoint used to configure kubectl
    # Env var: GANGWAY_APISERVER_URL
    # apiServerURL: "https://${GANGWAY_APISERVER_URL}"
    apiServerURL: "https://cluster.example.com"

    # The path to find the CA bundle for the API server. Used to configure kubectl.
    # This is typically mounted into the default location for workloads running on
    # a Kubernetes cluster and doesn't need to be set.
    # Env var: GANGWAY_CLUSTER_CA_PATH
    # cluster_ca_path: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"

    # The path gangway uses to create urls (defaults to "")
    # Env var: GANGWAY_HTTP_PATH
    #httpPath: "https://${GANGWAY_HTTP_PATH}"

**Current gangway deployment:**

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gangway
  namespace: gangway
  labels:
    app: gangway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gangway
  strategy:
  template:
    metadata:
      labels:
        app: gangway
        revision: "1"
    spec:
      containers:
        - name: gangway
          image: gcr.io/heptio-images/gangway:v2.2.0
          imagePullPolicy: Always
          command: ["gangway", "-config", "/gangway/gangway.yaml"]
          env:
            - name: GANGWAY_SESSION_SECURITY_KEY
              valueFrom:
                secretKeyRef:
                  name: gangway-key
                  key: sesssionkey
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          volumeMounts:
            - name: gangway
              mountPath: /gangway/
            - name: ca
              mountPath: /etc/gangway/tls/
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 60
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: gangway
          configMap:
            name: gangway
        - name: ca
          configMap:
            name: ca
            items:
            - key: ca.pem
              path: ca.pem

**Log auth dex:**

time="2018-10-25T22:57:13Z" level=info msg="config using log level: debug"
time="2018-10-25T22:57:13Z" level=info msg="config issuer: https://dex.k8s.dev.mta4.ru/"
time="2018-10-25T22:57:13Z" level=info msg="kubernetes client apiVersion = dex.coreos.com/v1"
time="2018-10-25T22:57:13Z" level=info msg="creating custom Kubernetes resources"
time="2018-10-25T22:57:13Z" level=info msg="custom resource already created authcodes.dex.coreos.com"
time="2018-10-25T22:57:13Z" level=info msg="custom resource already created authrequests.dex.coreos.com"
time="2018-10-25T22:57:13Z" level=info msg="custom resource already created oauth2clients.dex.coreos.com"
time="2018-10-25T22:57:13Z" level=info msg="custom resource already created signingkeies.dex.coreos.com"
time="2018-10-25T22:57:13Z" level=info msg="custom resource already created refreshtokens.dex.coreos.com"
time="2018-10-25T22:57:13Z" level=info msg="custom resource already created passwords.dex.coreos.com"
time="2018-10-25T22:57:13Z" level=info msg="custom resource already created offlinesessionses.dex.coreos.com"
time="2018-10-25T22:57:13Z" level=info msg="custom resource already created connectors.dex.coreos.com"
time="2018-10-25T22:57:13Z" level=info msg="config storage: kubernetes"
time="2018-10-25T22:57:13Z" level=info msg="config static client: gangway"
time="2018-10-25T22:57:13Z" level=info msg="config connector: ldap"
time="2018-10-25T22:57:13Z" level=info msg="config skipping approval screen"
time="2018-10-25T22:57:13Z" level=info msg="listening (http/telemetry) on 0.0.0.0:5558"
time="2018-10-25T22:57:13Z" level=info msg="listening (http) on 0.0.0.0:5556"
time="2018-10-25T23:00:46Z" level=info msg="performing ldap search OU=k8s,DC=dev,DC=mta4,DC=ru sub (&(objectClass=person)(sAMAccountName=user1))" connector=LDAP
time="2018-10-25T23:00:46Z" level=info msg="username \"user1\" mapped to entry CN=user1,OU=k8s,DC=dev,DC=mta4,DC=ru" connector=LDAP
time="2018-10-25T23:00:46Z" level=error msg="ldap: invalid password for user \"CN=user1,OU=k8s,DC=dev,DC=mta4,DC=ru\"" connector=LDAP
time="2018-10-25T23:01:04Z" level=info msg="performing ldap search OU=k8s,DC=dev,DC=mta4,DC=ru sub (&(objectClass=person)(sAMAccountName=user1))" connector=LDAP
time="2018-10-25T23:01:04Z" level=info msg="username \"user1\" mapped to entry CN=user1,OU=k8s,DC=dev,DC=mta4,DC=ru" connector=LDAP
time="2018-10-25T23:01:04Z" level=error msg="Failed to login user: ldap: entry \"CN=user1,OU=k8s,DC=dev,DC=mta4,DC=ru\" missing following required attribute(s): [\"mail\"]"
time="2018-10-25T23:01:54Z" level=info msg="performing ldap search OU=k8s,DC=dev,DC=mta4,DC=ru sub (&(objectClass=person)(sAMAccountName=user1))" connector=LDAP
time="2018-10-25T23:01:54Z" level=info msg="username \"user1\" mapped to entry CN=user1,OU=k8s,DC=dev,DC=mta4,DC=ru" connector=LDAP
time="2018-10-25T23:01:54Z" level=info msg="login successful: connector \"ldap\", username=\"user1\", email=\"user1@dev.mta4.ru\", groups=[]"

**Log auth gangway:**

time="2018-10-25T23:07:16Z" level=info msg="GET / 10.244.2.0:45312"
time="2018-10-25T23:07:17Z" level=info msg="GET /js/materialize.js 10.244.2.0:45312"
time="2018-10-25T23:07:17Z" level=info msg="GET /js/init.js 10.244.2.0:45314"
time="2018-10-25T23:07:26Z" level=info msg="GET / 10.244.1.1:36756"
time="2018-10-25T23:07:27Z" level=info msg="GET / 10.244.1.1:36758"
time="2018-10-25T23:07:36Z" level=info msg="GET / 10.244.1.1:36760"
time="2018-10-25T23:07:46Z" level=info msg="GET / 10.244.1.1:36762"
time="2018-10-25T23:07:56Z" level=info msg="GET / 10.244.1.1:36764"
time="2018-10-25T23:08:02Z" level=info msg="GET /login 10.244.2.0:45352"
time="2018-10-25T23:08:06Z" level=info msg="GET / 10.244.1.1:36766"
time="2018-10-25T23:08:13Z" level=info msg="GET /callback?code=mk62mmbmmarfvv7lple7smd36&state=HmaKW98sf8SERZLSVyvNBmjS1sUvUFTi0INr%2BExxdMs%3D 10.244.2.0:45366"
time="2018-10-25T23:08:16Z" level=info msg="GET / 10.244.1.1:36772"

**My self-sign cert script example:**

#!/bin/bash

mkdir -p ssl

cat << EOF > ssl/req.cnf
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name

[req_distinguished_name]

[v3_req]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names

[alt_names]
DNS.1 = dex.k8s.dev.mta4.ru
DNS.2 = login.k8s.dev.mta4.ru
DNS.3 = gangway.k8s.dev.mta4.ru
EOF

openssl genrsa -out ssl/ca-key.pem 2048
openssl req -x509 -new -nodes -key ssl/ca-key.pem -days 3650 -out ssl/ca.pem -subj "/CN=kube-oidc-auth-ca"


openssl genrsa -out ssl/dex.k8s.dev.mta4.ru-key.pem 2048
openssl req -new -key ssl/dex.k8s.dev.mta4.ru-key.pem -out ssl/dex.k8s.dev.mta4.ru.csr -subj "/CN=dex.k8s.dev.mta4.ru" -config ssl/req.cnf
openssl x509 -req -in ssl/dex.k8s.dev.mta4.ru.csr -CA ssl/ca.pem -CAkey ssl/ca-key.pem -CAcreateserial -out ssl/dex.k8s.dev.mta4.ru.pem -days 3650 -extensions v3_req -extfile ssl/req.cnf


openssl genrsa -out ssl/gangway.k8s.dev.mta4.ru-key.pem 2048
openssl req -new -key ssl/gangway.k8s.dev.mta4.ru-key.pem -out ssl/gangway.k8s.dev.mta4.ru.csr -subj "/CN=gangway.k8s.dev.mta4.ru" -config ssl/req.cnf
openssl x509 -req -in ssl/gangway.k8s.dev.mta4.ru.csr -CA ssl/ca.pem -CAkey ssl/ca-key.pem -CAcreateserial -out ssl/gangway.k8s.dev.mta4.ru.pem -days 3650 -extensions v3_req -extfile ssl/req.cnf

kubectl create secret tls dex.k8s.dev.mta4.ru.tls --cert=ssl/dex.k8s.dev.mta4.ru.pem --key=ssl/dex.k8s.dev.mta4.ru-key.pem -n dex

kubectl create secret tls gangway.k8s.dev.mta4.ru.tls --cert=ssl/gangway.k8s.dev.mta4.ru.pem --key=ssl/gangway.k8s.dev.mta4.ru-key.pem -n gangway

**Comment by rlagutinhub** [comment]
It worked for me, after recreate custom docker image:

![123](https://user-images.githubusercontent.com/30324030/47575000-ab9f8b80-d949-11e8-9da1-34b53d60ab14.png)

There is a possibility without creating custom docker image?

![screenshot-gangway k8s dev mta4 ru-2018-10-26-18-00-26-357](https://user-images.githubusercontent.com/30324030/47574806-1ef4cd80-d949-11e8-9b83-01a6a729424a.png)

**Comment by stpabhi** [comment]
Had the same problem with self-signed certs. Setting the below property worked for me on k8s.
**trustedCAPath: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"**

**Comment by rlagutinhub** [comment]
> @rlagutinhub can you try again and update your config file from: `TrustedCAPath` to `trustedCAPath`? The yaml parsing is case sensitive and my guess is when you set this param, it didn't get parsed and wasn't set.
> 
> When you load that config item up, it should be added to teh root ca's like you did when adding via the dockerfile: https://github.com/heptiolabs/gangway/blob/master/internal/config/transport.go#L44

yes it works)

Another problem
oidc via ldap+dex - invalid bearer token, invalid bearer token https://github.com/kubernetes/kubernetes/issues/70601

**Comment by rlagutinhub** [comment]
> Another problem
> oidc via ldap+dex - invalid bearer token, invalid bearer token
> kubernetes/kubernetes#70601
> dexidp/dex#1336

> It is very possible that reason for error **[invalid bearer token, [invalid bearer token, invalid bearer token]]** ,
> 
> what I do backup manifest kube-api config file before changing it
> **cp -p /etc/kubernetes/manifests/kube-apiserver.yaml /etc/kubernetes/manifests/kube-apiserver.yaml.orig**

really), after deleting this backup file /etc/kubernetes/manifests/kube-apiserver.yaml.orig
it works

for information https://github.com/dexidp/dex/issues/1336

**Comment by jonbesga** [comment]
Hi, I'm having the same problem but can't get to solve it with the information above.

My current configMap and deployment are:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: gangway
  namespace: auth-system
data:
  gangway.yaml: |
    clusterName: "K8S"
    apiServerURL: "https://10.64.160.231:6443"
    authorizeURL: "https://auth.kubernetes.domain.net/auth"
    tokenURL: "https://auth.kubernetes.domain.net/token"
    clientID: "oidc-auth-client"
    clientSecret: "*******************"
    redirectURL: "https://kubectl.kubernetes.domain.net/callback"
    scopes: ["openid", "profile", "email", "offline_access"]
    usernameClaim: "email"
    emailClaim: "email"
    trustedCAPath: "/cacerts/tls.crt"
```

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gangway
  namespace: auth-system
  labels:
    app: gangway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gangway
  strategy:
  template:
    metadata:
      labels:
        app: gangway
        revision: "1"
    spec:
      containers:
        - name: gangway
          image: gcr.io/heptio-images/gangway:v2.0.0
          imagePullPolicy: Always
          command: ["gangway", "-config", "/gangway/gangway.yaml"]
          env:
            - name: GANGWAY_SESSION_SECURITY_KEY
              valueFrom:
                secretKeyRef:
                  name: gangway-key
                  key: sesssionkey
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
          volumeMounts:
            - name: gangway
              mountPath: /gangway/
            - name: ca
              mountPath: /cacerts/
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 60
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: gangway
          configMap:
            name: gangway
        - name: ca
          secret:
            secretName: rootca
```

And the secret *rootca* was creating using:

For the root certificate:
`openssl genrsa -des3 -out rootCA.key 4096`

`openssl req -x509 -new -nodes -key rootCA.key -sha256 -days 1024 -out rootCA.crt`

`kubectl create secret tls rootCA --key rootCA.key --cert rootCA.crt --namespace auth-system`

For creating the certificates I followed the following [steps](https://gist.github.com/fntlnz/cf14feb5a46b2eda428e000157447309):

For the certificate used when loading gangway:

`openssl genrsa -out auth.kubernetes.domain.net.key 2048`

`openssl req -new -sha256 -key auth.kubernetes.domain.net -subj "/C=US/ST=CA/O=MyOrg, Inc./CN=auth.kubernetes.domain.net" -out auth.kubernetes.domain.net.csr`

`openssl x509 -req -in auth.kubernetes.domain.net.csr -CA rootCA.crt -CAkey rootCA.key -CAcreateserial -out auth.kubernetes.domain.net.crt -days 500 -sha256`

`kubectl create secret tls auth.kubernetes.domain.net --key auth.kubernetes.domain.net.key --cert auth.kubernetes.domain.net.crt`

Which is used in the following daemonset (I have a nginx daemonset in the nodes so I don't use Ingress):

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: nginx:1.15.3-alpine
        name: nginx
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
        volumeMounts:
        - name: "config"
          mountPath: "/etc/nginx"
        - name: secret-volume
          mountPath: /etc/nginx/ssl
      volumes:
      - name: config
        configMap:
          name: nginx-conf
      - name: secret-volume
        secret:
           secretName: auth.kubernetes.domain.net

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    worker_processes 1;
    error_log /dev/stdout info;

    events {
      worker_connections 10;
    }

    http {
      access_log /dev/stdout;
     
      server {
        listen 443 ssl;
        server_name auth.kubernetes.domain.net;
        ssl_certificate /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;

        location / {
          proxy_pass http://dex.auth-system.svc.cluster.local:5556;
        }
      }
      server {
        server_name kubectl.kubernetes.domain.net
        ssl_certificate /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;
        listen 443 ssl;
        #listen 80;
        location / {
          proxy_pass http://gangway-svc.auth-system.svc.cluster.local:80;
        }
      }
   }

```
